### ISSUE TITLE
软件包

### ISSUE THREAD

**Issue by 160725** [PaiGramTeam/HonkaiStarRailWikiDataParser#1]
能编译好直接发包吗？

**Comment by omg-xtao** [comment]
@160725 你好，此解析器只是一个解析游戏数据并将其保存为 JSON 文件的脚本，而不是一个完整的软件包。此外，此仓库将会在解析代码更新时自动更新数据到 remote 分支的 data 文件夹内。如果发布软件包，用户将无法自动获得最新数据，这会影响使用体验。因此，这个操作没有必要。

**Comment by 160725** [comment]
其实我是希望你能开发一个和snap hutao（https://hut.ao/zh/）一样的软件用于星穹铁道的，推出pc版、安卓版、ios版和小程序，因为现在此类软件属于空白期，暂时好像也没人做，也不知道他们现在有没有开发。
没有这类软件真的有点难受

**Comment by luoshuijs** [comment]
目前我们人就这点，而且大家基本都有事。这个重磅任务还是交给其他大佬们吧。毕竟这些也不是几周就能写完的东西。如果没什么问题我就关闭这个issue了。
