### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by 0x8ubb1e** [PaiGramTeam/HonkaiStarRailWikiDataParser#2]
models下avatar.py编译过程中 一直提示AvatarPromote类下的`items: list[AvatarItem]`不可有下标
我的python是3.8.7

`Traceback (most recent call last):`
`  File "D:/HonkaiStarRailWikiDataParser-main/main.py", line 4, in <module>`
`    from func.fetch_avatars import fetch_avatars, fetch_avatars_infos, dump_avatars, read_avatars`
`  File "D:\HonkaiStarRailWikiDataParser-main\func\fetch_avatars.py", line 14, in <module>`
`    from models.avatar import Avatar, AvatarInfo, AvatarSoul, AvatarItem, AvatarPromote`
`  File "D:\HonkaiStarRailWikiDataParser-main\models\avatar.py", line 21, in <module>`
`    class AvatarPromote(BaseModel):`
`  File "D:\HonkaiStarRailWikiDataParser-main\models\avatar.py", line 31, in AvatarPromote`
`    items: list[AvatarItem]`
`TypeError: 'type' object is not subscriptable`

**Comment by luoshuijs** [comment]
这个错误的原因是你试图在 Python 版本不支持的情况下使用类型提示（type hinting）。在你的代码中，`list[AvatarItem]` 这个语法是在 Python 3.9 中引入的。在 Python 3.9 或更高版本，你可以用这种方式来指定列表中元素的类型。但是，如果你使用的是 Python 3.8 或更低版本，这样做就会导致错误。
建议：使用 Python 3.9 或更高版本

**Comment by luoshuijs** [comment]
当然，你也可以提交一个Pr。更改类型提示的语法以适应你当前的 Python 版本。在 Python 3.8 或更低版本中，你需要使用 `typing.List` 来代替 `list`，并将元素类型放在方括号内。
